### ISSUE TITLE
Code in c++

### ISSUE THREAD

**Issue by smtechnogeek** [smtechnogeek/Code_here_hacktober2022#1]
code hello world

**Comment by mukulbaghel** [comment]
hey I would like to do work on this issue .
Can u assign me this ?

**Comment by Vanshika-Batra** [comment]
I'd like to work on this. Could you please assign it to me?

**Comment by smtechnogeek** [comment]
> I'd like to work on this. Could you please assign it to me?

yes u can simply create a pull request

**Comment by smtechnogeek** [comment]
> hey I would like to do work on this issue . Can u assign me this ?

yes u can
